"""Architecture diagram schemas: components, connections, and trust boundaries.

These structures represent the output of the diagram extraction stage (e.g. LLM vision):
they describe what was detected in the image and feed into STRIDE/DREAD threat analysis.
"""

from enum import Enum

from pydantic import Field

from .base import BaseSchema


class ComponentType(str, Enum):
    """Standard types of architecture components recognised by the analyzer.

    Used to classify nodes in the diagram (users, servers, databases, gateways, etc.)
    for consistent threat modelling and risk assessment.
    """

    USER = "User"
    CLIENT = "Client"
    SERVER = "Server"
    DATABASE = "Database"
    GATEWAY = "Gateway"
    LOAD_BALANCER = "LoadBalancer"
    CACHE = "Cache"
    QUEUE = "Queue"
    STORAGE = "Storage"
    API = "API"
    SERVICE = "Service"
    EXTERNAL_SERVICE = "ExternalService"
    OTHER = "Other"


class Component(BaseSchema):
    """A single node in the architecture diagram (actor, server, DB, etc.).

    Each component is identified by an id (used in connections and threat references),
    has a type (e.g. Server, Database), a display name, and an optional description
    extracted from the diagram or generated by the model.
    """

    id: str = Field(
        ...,
        description="Unique identifier for the component; referenced by connections and threats.",
    )
    type: str = Field(
        ...,
        description="Component type (e.g. Server, Database, API) as classified by the analyzer.",
    )
    name: str = Field(
        ...,
        description="Human-readable name of the component as shown or inferred from the diagram.",
    )
    description: str | None = Field(
        default=None,
        description="Optional description of the component's role or technology.",
    )


class Connection(BaseSchema):
    """A directed link between two components (data flow or dependency).

    Represents communication or data movement from a source component to a target.
    Protocol and encryption hints improve threat analysis (e.g. unencrypted flows).
    """

    from_id: str = Field(
        ...,
        alias="from",
        description="Id of the source component (where the connection originates).",
    )
    to_id: str = Field(
        ...,
        alias="to",
        description="Id of the target component (where the connection ends).",
    )
    protocol: str | None = Field(
        default=None,
        description="Communication protocol if known (e.g. HTTPS, gRPC, AMQP).",
    )
    description: str | None = Field(
        default=None,
        description="Optional description of the connection or data exchanged.",
    )
    encrypted: bool | None = Field(
        default=None,
        description="Whether the connection is encrypted (True/False) or unknown (None).",
    )


class TrustBoundary(BaseSchema):
    """A boundary that separates zones of different trust levels (e.g. DMZ, VPC, subnet).

    Components inside the same boundary share a trust context; crossing boundaries
    is a common point for threat analysis (e.g. data exfiltration, privilege escalation).
    """

    name: str = Field(
        ...,
        description='Name of the trust boundary (e.g. "DMZ", "Private subnet").',
    )
    components: list[str] = Field(
        default_factory=list,
        description="List of component ids that belong to this trust boundary.",
    )


class DiagramData(BaseSchema):
    """Structured representation of the architecture diagram after extraction.

    Contains the model that performed the extraction, the list of detected components
    and connections, and the list of trust boundary names. Used internally in the
    pipeline before STRIDE/DREAD analysis.
    """

    model: str = Field(
        ...,
        description="Identifier of the model used for diagram extraction (e.g. gemini-1.5-pro).",
    )
    components: list[Component] = Field(
        default_factory=list,
        description="All components detected in the diagram.",
    )
    connections: list[Connection] = Field(
        default_factory=list,
        description="All connections (data flows / dependencies) between components.",
    )
    boundaries: list[str] = Field(
        default_factory=list,
        description="Names of trust boundaries detected in the diagram.",
    )
